############################################################
# Kubernetes Namespace
############################################################

apiVersion: v1

kind: Namespace


metadata:

  name: gitops-app


  labels:

    app: gitops-app

    environment: dev
