############################################################
# Flask Application Service
############################################################

apiVersion: v1

kind: Service


metadata:

  name: gitops-app-service

  namespace: gitops-app


  labels:

    app: gitops-app



spec:

  selector:

    app: gitops-app



  ports:

    - protocol: TCP

      port: 80

      targetPort: 5000



  type: ClusterIP
