############################################################
# Kubernetes Service Account
############################################################

apiVersion: v1

kind: ServiceAccount


metadata:

  name: gitops-app-sa

  namespace: gitops-app


  labels:

    app: gitops-app
