name: Helm Deploy


on:

  push:

    branches:

      - main



jobs:


  deploy:


    name: Deploy to Kubernetes


    runs-on: ubuntu-latest



    steps:


      - name: Checkout Repository

        uses: actions/checkout@v4



      - name: Setup Helm

        uses: azure/setup-helm@v4



      - name: Helm Lint

        run: |

          helm lint ./helm/gitops-app
         - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: ap-south-1



      - name: Configure Kubernetes Context

        run: |

          aws eks update-kubeconfig \
          --name ${{ secrets.EKS_CLUSTER_NAME }} \
          --region ap-south-1



      - name: Deploy Helm Release

        run: |

          helm upgrade --install gitops-app \
          ./helm/gitops-app \
          --namespace gitops-app \
          --create-namespace 
