############################################################
# ArgoCD Application
############################################################

apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:

  name: gitops-app

  namespace: argocd

spec:

  project: gitops-project

  source:

    repoURL: "https://github.com/YOUR_GITHUB_USERNAME/gitops-multicloud-platform.git"

    targetRevision: main

    path: helm/gitops-app

    helm:

      valueFiles:

        - values.yaml

  destination:

    server: https://kubernetes.default.svc

    namespace: gitops-app

  syncPolicy:

    automated:

      prune: true

      selfHeal: true

    syncOptions:

      - CreateNamespace=true
      repoURL: "https://github.com/singhanjali33375-rgb/gitops-multicloud-platform.git"
