apiVersion: v1
kind: Namespace
metadata:
  name: falco

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco
  namespace: falco

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: falco
  labels:
    app: falco
spec:
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
    spec:
      serviceAccountName: falco
      hostPID: true
      hostNetwork: true
      containers:
        - name: falco
          image: falcosecurity/falco:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          args:
            - /usr/bin/falco
            - -K=/var/run/secrets/kubernetes.io/serviceaccount/token
          volumeMounts:
            - name: dev-fs
              mountPath: /host/dev
            - name: proc-fs
              mountPath: /host/proc
            - name: boot-fs
              mountPath: /host/boot
      volumes:
        - name: dev-fs
          hostPath:
            path: /dev
        - name: proc-fs
          hostPath:
            path: /proc
        - name: boot-fs
          hostPath:
            path: /boot
