apiVersion: apps/v1

kind: Deployment


metadata:

  name: {{ include "gitops-app.fullname" . }}

  labels:

    {{- include "gitops-app.labels" . | nindent 4 }}



spec:

  replicas: {{ .Values.replicaCount }}


  selector:

    matchLabels:

      {{- include "gitops-app.selectorLabels" . | nindent 6 }}



  template:

    metadata:

      labels:

        {{- include "gitops-app.selectorLabels" . | nindent 8 }}



    spec:

      containers:

        - name: gitops-app


          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"


          imagePullPolicy: {{ .Values.image.pullPolicy }}


          ports:

            - name: http

              containerPort: {{ .Values.container.port }}



          env:

            - name: ENVIRONMENT

              value: {{ .Values.env.ENVIRONMENT }}


            - name: APP_NAME

              value: {{ .Values.env.APP_NAME }}



          resources:

            {{- toYaml .Values.resources | nindent 12 }}



          readinessProbe:

            httpGet:

              path: /health

              port: http


            initialDelaySeconds: 10

            periodSeconds: 5



          livenessProbe:

            httpGet:

              path: /health

              port: http


            initialDelaySeconds: 30

            periodSeconds: 10
