############################################################
# Flask Application Deployment
############################################################

apiVersion: apps/v1

kind: Deployment


metadata:

  name: gitops-app

  namespace: gitops-app


  labels:

    app: gitops-app



spec:

  replicas: 2


  selector:

    matchLabels:

      app: gitops-app



  template:

    metadata:

      labels:

        app: gitops-app



    spec:

      serviceAccountName: gitops-app-sa


      containers:

        - name: flask-container


          image: YOUR_DOCKERHUB_USERNAME/gitops-app:latest


          imagePullPolicy: Always


          ports:

            - containerPort: 5000


          envFrom:

            - configMapRef:

                name: gitops-app-config
                readinessProbe:

            httpGet:

              path: /health

              port: 5000


            initialDelaySeconds: 10

            periodSeconds: 5



          livenessProbe:

            httpGet:

              path: /health

              port: 5000


            initialDelaySeconds: 30

            periodSeconds: 10



          resources:

            requests:

              cpu: "100m"

              memory: "128Mi"


            limits:

              cpu: "500m"

              memory: "512Mi"



          securityContext:

            runAsNonRoot: true

            allowPrivilegeEscalation: false
